const IMGS = {"노트릴스_영상": "https://crocdeucation-rgb.github.io/image/report/소재/notereels_video.jpg", "GT노트피드백_영상": "https://crocdeucation-rgb.github.io/image/report/소재/gtnote_video.jpg", "너만본다_영상": "https://crocdeucation-rgb.github.io/image/report/소재/neoman_video.jpg", "5단계루틴": "https://crocdeucation-rgb.github.io/image/report/소재/routine5.jpg", "기초부족": "https://crocdeucation-rgb.github.io/image/report/소재/basic.jpg", "비평준화": "https://crocdeucation-rgb.github.io/image/report/소재/bipyeong.jpg", "노트릴스_5월": "https://crocdeucation-rgb.github.io/image/report/소재/notereels_may.jpg", "GT노트피드백_5월": "https://crocdeucation-rgb.github.io/image/report/소재/gtnote_may.jpg", "과외저격": "https://crocdeucation-rgb.github.io/image/report/소재/tutoring.jpg", "기말고사대비": "https://crocdeucation-rgb.github.io/image/report/소재/finalexam.jpg", "체크리스트": "https://crocdeucation-rgb.github.io/image/report/소재/checklist.jpg", "중간고사이후": "https://crocdeucation-rgb.github.io/image/report/소재/midexam.jpg", "노트릴스_채리_2606": "https://crocdeucation-rgb.github.io/image/report/소재/notereels_chaeri.jpg", "텐핑_공부습관무료검사": "https://crocdeucation-rgb.github.io/image/report/소재/tenping_habit.jpg", "텐핑_공부잘하고싶은": "https://crocdeucation-rgb.github.io/image/report/소재/tenping_want.jpg", "텐핑_교육부인가": "https://crocdeucation-rgb.github.io/image/report/소재/tenping_edu.jpg", "텐핑_맘카페난리": "https://crocdeucation-rgb.github.io/image/report/소재/tenping_mom.jpg", "텐핑_광주시모집": "https://crocdeucation-rgb.github.io/image/report/소재/tenping_gwangju.jpg", "텐핑_서울시무료검사": "https://crocdeucation-rgb.github.io/image/report/소재/tenping_seoul.jpg", "mlst_v1": "https://crocdeucation-rgb.github.io/image/report/소재/daangn_v1.png", "mlst_v2": "https://crocdeucation-rgb.github.io/image/report/소재/daangn_v2.png", "mlst_v3": "https://crocdeucation-rgb.github.io/image/report/소재/daangn_v3.png", "mlst_v4": "https://crocdeucation-rgb.github.io/image/report/소재/daangn_v4.png", "캐러셀_1_표지": "https://crocdeucation-rgb.github.io/image/report/소재/carousel_1.png", "캐러셀_2_고민": "https://crocdeucation-rgb.github.io/image/report/소재/carousel_2.png", "캐러셀_3_MLST검사": "https://crocdeucation-rgb.github.io/image/report/소재/carousel_3.png", "캐러셀_4_결과": "https://crocdeucation-rgb.github.io/image/report/소재/carousel_4.png", "캐러셀_5_CTA": "https://crocdeucation-rgb.github.io/image/report/소재/carousel_5.png", "노트필기릴스_2607": "https://crocdeucation-rgb.github.io/image/report/소재/notefilgi_2607.png",
"릴스_방으로": "https://crocdeucation-rgb.github.io/image/report/소재/goroom_now.jpg",
"릴스_박은영중간고사": "https://crocdeucation-rgb.github.io/image/report/소재/oneshot_eunyoung_mid.jpg",
"릴스_맞춤처방": "https://crocdeucation-rgb.github.io/image/report/소재/oneshot_prescription.jpg",
"캐러셀_중간고사전략": [
  "https://crocdeucation-rgb.github.io/image/report/소재/carousel_mid_1.png",
  "https://crocdeucation-rgb.github.io/image/report/소재/carousel_mid_2.png",
  "https://crocdeucation-rgb.github.io/image/report/소재/carousel_mid_3.png",
  "https://crocdeucation-rgb.github.io/image/report/소재/carousel_mid_4.png"
],
"단일_시험기간": "https://crocdeucation-rgb.github.io/image/report/소재/single_examweek.png",
"단일_노트": "https://crocdeucation-rgb.github.io/image/report/소재/single_note.png",
"단일_Dday": "https://crocdeucation-rgb.github.io/image/report/소재/single_dday.png",
"단일_맘카페": "https://crocdeucation-rgb.github.io/image/report/소재/single_momcafe.png",
"단일_공부습관": "https://crocdeucation-rgb.github.io/image/report/소재/single_habit.png"};
